### ISSUE TITLE
Patch 11 has a click

### ISSUE THREAD

**Issue by drepetto** [bwhitman/amy#46]
when I do:
alles.send(osc=0,wave=alles.PCM,vel=0.3,patch=11)

there's a click in the resulting drum sound.

**Comment by dpwe** [comment]
Are you saying there's no click when vel=0.2 or something?  I'm having trouble hearing the difference.

**Comment by dpwe** [comment]
(I want to look at the waveform, but my employer forced me to remove AudioHijack from my desktop, and my oscilloscope is not attached to my Tulip ATM)

**Comment by bwhitman** [comment]
Alles has a "write to raw file" parameter I believe

**Comment by drepetto** [comment]
> 

When I do this:
> alles.send(osc=0,wave=alles.PCM,vel=0.75,patch=11)

I hear a click when the sample plays. It feels like it's not actually at the very beginning of the sample, but it's very short, so it's difficult to tell. But it's a consistent click that does not seem to be there on purpose, given the pitched drum sound.

**Comment by drepetto** [comment]
Sorry if my first post was unclear -- I don't think the click is velocity dependent. I think it's either in the sample data or the sample data is being read at an offset so there's a discontinuity.

**Comment by dpwe** [comment]
Fixed in [ed850fa](https://github.com/bwhitman/amy/commit/ed850fae241039652ffa0912140788e6ecefb1d9) and [2442329](https://github.com/bwhitman/amy/commit/2442329b79e0015a88fa58eed2da3ad3862de202).  When `amy_headers.py` was writing the `pcm_samples_*.h` files, it normalized the amplitudes to a max of 32768 instead of 32767, so the single instance of +1.0 mapped to -32768, which made a nasty click.  Good ears!
